"""Transactions table update A

Revision ID: 6040eba19ddb
Revises: 907e168f180d
Create Date: 2025-07-15 13:46:08.099356
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6040eba19ddb'
down_revision = '907e168f180d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_response',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('response_code', sa.String(length=10), nullable=False),
        sa.Column('response_description', sa.String(length=255), nullable=True),
        sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
        sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
        sa.Column('result_code', sa.String(length=10), nullable=True),
        sa.Column('result_description', sa.String(length=255), nullable=True),
        sa.Column('raw_callback', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.String(length=100), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('transaction_id')
    )

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_payments_user_id', 'users', ['user_id'], ['id'])  # ✅ Named foreign key

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_user_id', type_='foreignkey')  # ✅ Use correct constraint name
        batch_op.drop_column('user_id')

    op.drop_table('transactions')
    op.drop_table('payment_response')
    # ### end Alembic commands ###
