""" relationships fixed

Revision ID: 907e168f180d
Revises: 25b907eaf4e5
Create Date: 2025-07-07 13:34:32.242417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907e168f180d'
down_revision = '25b907eaf4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='order_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='order_status'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
