"""Relationships update

Revision ID: d2816602bd2c
Revises: 6040eba19ddb
Create Date: 2025-07-17 10:56:38.489924
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2816602bd2c'
down_revision = '6040eba19ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_payments_user_id', 'users', ['user_id'], ['id'])  # ✅ Explicit name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_user_id', type_='foreignkey')  # ✅ Match the name here
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
