"""Add product_id to CartItem

Revision ID: f35bd19ff2e2
Revises: 7b854929857a
Create Date: 2025-07-07 11:57:59.892673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35bd19ff2e2'
down_revision = '7b854929857a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False, server_default='1'))  # Added server_default
        batch_op.create_foreign_key(
            'fk_cart_items_product_id',  # Named constraint
            'products', 
            ['product_id'], 
            ['product_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_items_product_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
